/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import AccessBD.Faire_Connection;
import AccessBD.MethodesBD;
import Class.Billet;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;

public class Gestion_Dossier extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static Connection conn = Faire_Connection.getConnexion();
    /**
     * Creates new form Gestion_Dossier
     */
    public Gestion_Dossier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nodossier = new javax.swing.JTextField();
        txt_prixtotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_place = new javax.swing.JTable();
        btn_supprime_place = new javax.swing.JButton();
        recheche = new javax.swing.JButton();
        btn_supprimer_dossier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("GESTION DOSSIERS");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("DOSSIER");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("PRIX TOTAL");

        tab_place.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serie", "Numero Spectacle", "Date Representation", "Rang", "Place", "Date Achat"
            }
        ) {
            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			@SuppressWarnings("rawtypes")
			Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class<?> getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_place);

        btn_supprime_place.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btn_supprime_place.setText("SUPPRIMER PlACE");
        btn_supprime_place.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_supprime_placeMouseClicked(evt);
            }
        });

        recheche.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        recheche.setText("RECHERCHE");
        recheche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechecheMouseClicked(evt);
            }
        });

        btn_supprimer_dossier.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_supprimer_dossier.setText("SUPPRIMER DOSSIER");
        btn_supprimer_dossier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_supprimer_dossierMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nodossier, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_prixtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(recheche))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btn_supprime_place, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btn_supprimer_dossier)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nodossier, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_prixtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recheche, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_supprime_place, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_supprimer_dossier, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rechecheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechecheMouseClicked
        actualiser_tab();
    }//GEN-LAST:event_rechecheMouseClicked
    
    /**
     * Actualiser le table après une fonction
     */
    private void actualiser_tab(){
        int noDossier = Integer.parseInt(txt_nodossier.getText());
        int prixTotal = 0;
        try {
            prixTotal = MethodesBD.methode_h(conn,noDossier);
        } catch (SQLException ex) {
            Logger.getLogger(Gestion_Dossier.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_prixtotal.setText(Integer.toString(prixTotal));
        
        HashSet<Billet> liste_billet = null;
        try {
            liste_billet = MethodesBD.methode_g(conn,noDossier);
        } catch (SQLException ex) {
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Iterator<Billet> iterator = liste_billet.iterator(); 
        DefaultTableModel model=(DefaultTableModel) tab_place.getModel();
        model.setRowCount(0);
        while (iterator.hasNext()){            
            Billet bil=iterator.next(); 
            model.addRow(new Object[]{bil.getNoSerie(),bil.getNumS(),bil.getDateRep(),bil.getNoRang(),bil.getNoPlace(),bil.getDateEmission()});
        }
    }
    
    /**
     * Supprimer une seul place
     */
    private void btn_supprime_placeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supprime_placeMouseClicked
        int row=tab_place.getSelectedRow();
        int noSerie = Integer.parseInt(tab_place.getModel().getValueAt(row,0).toString());
        int noRang = Integer.parseInt(tab_place.getModel().getValueAt(row,3).toString());
        int noPlace = Integer.parseInt(tab_place.getModel().getValueAt(row,4).toString());
        int noDossier = Integer.parseInt(txt_nodossier.getText());
        
        try {
            MethodesBD.methode_m(conn,noSerie,noRang,noPlace,noDossier);
            actualiser_tab();
        } catch (SQLException ex) {
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_supprime_placeMouseClicked

    /**
     * Supprime Dossier
     */
    private void btn_supprimer_dossierMouseClicked(java.awt.event.MouseEvent evt) {
 
        int noDossier = Integer.parseInt(txt_nodossier.getText());
        DefaultTableModel model = (DefaultTableModel) tab_place.getModel();
        try {
            MethodesBD.methode_n(conn,noDossier);
            model.setNumRows(0);
            txt_prixtotal.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_supprimer_dossierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void Gestion() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_Dossier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_Dossier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_Dossier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_Dossier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_Dossier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_supprime_place;
    private javax.swing.JButton btn_supprimer_dossier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton recheche;
    private javax.swing.JTable tab_place;
    private javax.swing.JTextField txt_nodossier;
    private javax.swing.JTextField txt_prixtotal;
    // End of variables declaration//GEN-END:variables
}
